import type { LegalPassage } from "../types";

type P = Partial<LegalPassage> & Pick<LegalPassage, "id" | "sourceId" | "ref" | "heading" | "text" | "jurisdiction">;

function p(x: P): LegalPassage {
  return {
    textKind: "paraphrase",
    effectiveFrom: "2025-01-01",
    effectiveTo: null,
    topics: [],
    ruleIds: [],
    electionIds: [],
    instrumentIds: [],
    gapIds: [],
    ...x,
  };
}

const D = "TH-DECREE-2567";

/**
 * Domestic passages. Thailand follows the Revenue Department's Emergency
 * Decree and its subordinate notifications; the official text is Thai and
 * these are GMT24's English paraphrases. Ireland, Japan and the United States
 * are summaries at the level GMT24's rule pack uses them.
 */
export const DOMESTIC_PASSAGES: LegalPassage[] = [
  /* ---------------------------------------------------------- Thailand */
  p({ id: "LP-TH-D-S5", sourceId: D, ref: "s 5 — scope", heading: "In-scope MNE Group — THB threshold test", jurisdiction: "TH", text: "The Decree applies to an MNE Group whose consolidated revenue in the UPE's consolidated financial statements reaches the EUR 750 million threshold in at least two of the four accounting periods preceding the tested period, with the euro amount converted to baht at the Bank of Thailand rate prescribed by the Director-General (Notification No. 6). Periods shorter or longer than twelve months are prorated. Rules for groups formed by merger or demerger are delegated to subordinate legislation.", topics: ["thailand", "scope", "750m", "thb", "bank of thailand", "two of four"], ruleIds: ["TH-PACK-2567"], instrumentIds: ["prk2567", "dgtopuptax6"], gapIds: ["G-SCOPE"], href: "/thailand/scope" }),
  p({ id: "LP-TH-D-S9-12", sourceId: D, ref: "ss 9–12 — charge to Top-up Tax", heading: "Thai QDMTT, IIR and UTPR", jurisdiction: "TH", text: "Constituent Entities located in Thailand of an in-scope MNE Group are liable to domestic Top-up Tax — a Qualified Domestic Minimum Top-up Tax — where the group's effective tax rate in Thailand for the accounting period is below the 15% minimum rate, for accounting periods beginning on or after 1 January 2025. A Thai parent entity is liable under the Income Inclusion Rule for its allocable share of the Top-up Tax of low-taxed foreign Constituent Entities, and Thai Constituent Entities bear the Undertaxed Profits Rule adjustment allocated to Thailand, in each case after amounts collected by a qualified domestic minimum tax or qualified IIR elsewhere. Thai Constituent Entities are jointly and severally liable, and a group may designate a Thai taxpayer to file and pay for the others.", topics: ["thailand", "qdmtt", "iir", "utpr", "15%", "1 january 2025", "designated taxpayer", "joint and several"], ruleIds: ["TH-QDMTT-2025", "TH-PACK-2567"], instrumentIds: ["prk2567"], gapIds: ["G-ETR", "G-ORDER"], href: "/thailand/liability" }),
  p({ id: "LP-TH-D-INTERP", sourceId: D, ref: "interpretation clause", heading: "Interpretation in line with the GloBE Rules", jurisdiction: "TH", text: "The Decree is to be interpreted and applied consistently with the Global Anti-Base Erosion Model Rules, the Commentary and the Administrative Guidance agreed by the OECD/G20 Inclusive Framework, except where the Decree or a notification issued under it specifically provides otherwise. Thai instruments therefore override on the points they address and inherit the OECD text on everything else.", topics: ["thailand", "interpretation", "globe", "commentary", "override", "inherit"], ruleIds: ["TH-PACK-2567"], instrumentIds: ["prk2567"], gapIds: ["G-INTERP", "G-FANIL", "G-ETR"], href: "/thailand/gap" }),
  p({ id: "LP-TH-D-S31", sourceId: D, ref: "s 31 — GloBE income adjustments (delegated)", heading: "Detailed GloBE Income adjustments — instrument pending", jurisdiction: "TH", textKind: "pending", text: "Section 31 empowers the Director-General to prescribe the detailed adjustments from financial accounting net income or loss to GloBE Income for Thai purposes. Until the notification is issued, GMT24 applies the OECD Art. 3.2 adjustments under the interpretation clause and records the position as a coverage exception, not as Thai law.", topics: ["thailand", "section 31", "globe income", "pending", "delegated"], ruleIds: ["TH-PACK-2567"], instrumentIds: ["s31"], gapIds: ["G-FANIL"], href: "/thailand/gap" }),
  p({ id: "LP-TH-D-S33", sourceId: D, ref: "s 33 — Adjusted Covered Taxes (delegated)", heading: "Detailed Adjusted Covered Tax rules — instrument pending", jurisdiction: "TH", textKind: "pending", text: "Section 33 provides for the Director-General to prescribe the computation of Adjusted Covered Taxes, including deferred tax treatment. The covered-tax definition itself is in the Decree and Notification No. 2 covers imputation and refundable taxes; the detailed rules are not yet issued and GMT24 follows OECD Chapter 4 in the meantime.", topics: ["thailand", "section 33", "covered taxes", "deferred tax", "pending"], ruleIds: ["TH-PACK-2567"], instrumentIds: ["s33"], gapIds: ["G-CT"], href: "/thailand/gap" }),
  p({ id: "LP-TH-D-S54-58", sourceId: D, ref: "ss 54–58 — notification, return and payment", heading: "Thai filing and payment clocks", jurisdiction: "TH", text: "Within 15 months after the end of the accounting period a Thai Constituent Entity must notify the Revenue Department of the UPE and the entity that will file the GloBE Information Return (s 54); the GloBE Information Return is filed in Thailand or received through exchange (ss 55–56); and the Thai Top-up Tax return is filed and the tax paid (s 57). For the first accounting period in which the group is in scope the deadline is 18 months (s 58). The return forms and electronic submission schema are delegated to the Director-General and not yet prescribed.", topics: ["thailand", "filing", "section 54", "section 57", "15 months", "18 months", "notification", "payment"], ruleIds: ["TH-PACK-2567"], instrumentIds: ["prk2567", "s53-57"], gapIds: ["G-FILE"], href: "/thailand/filing" }),
  p({ id: "LP-TH-D-AUDIT", sourceId: D, ref: "assessment, penalties and appeal chapters", heading: "Assessment window, surcharge, penalties and appeal", jurisdiction: "TH", text: "Assessing officers may examine and assess Top-up Tax within ten years of the filing deadline and may call for information and documents. Under-declared tax attracts a penalty of one or two times the tax depending on the default, and a surcharge of 1.5% per month (0.75% where an extension was granted), capped at the amount of tax. Failure to file a required notification or return carries a fine of up to THB 200,000. An assessment may be appealed within 30 days.", topics: ["thailand", "audit", "assessment", "ten years", "penalty", "surcharge", "200,000", "appeal"], ruleIds: ["TH-PACK-2567"], instrumentIds: ["prk2567"], gapIds: ["G-AUDIT"], href: "/thailand/audit" }),
  p({ id: "LP-TH-DG1", sourceId: "TH-DG-1", ref: "Notification No. 1", heading: "Acceptable financial accounting standards", jurisdiction: "TH", text: "Lists the financial accounting standards accepted for computing GloBE Income in Thailand — Thai Financial Reporting Standards, IFRS and the standards of the listed jurisdictions — and the conditions for using a standard other than the UPE's: the information must be reliable, differences in presentation above the stated euro threshold must be documented, and permanent differences above EUR 1 million are conformed to the UPE's standard.", topics: ["thailand", "accounting standard", "tfrs", "ifrs", "whitelist", "eur 1 million"], ruleIds: ["TH-PACK-2567"], electionIds: ["OECD_3.1.3"], instrumentIds: ["dgtopuptax1"], gapIds: ["G-GAAP"], href: "/thailand/scope" }),
  p({ id: "LP-TH-DG2", sourceId: "TH-DG-2", ref: "Notification No. 2", heading: "Qualified and disqualified refundable imputation taxes", jurisdiction: "TH", text: "Sets the criteria for treating a tax on distributed profits as a Qualified Imputation Tax (refundable or creditable to the shareholder only where the shareholder is taxed at or above the minimum rate, or is a qualifying resident individual, government, international organisation, non-profit or pension fund) and for identifying Disqualified Refundable Imputation Taxes, which are excluded from Covered Taxes. Provides the questionnaire GMT24 mirrors in the covered-tax classification.", topics: ["thailand", "imputation tax", "disqualified", "covered taxes", "questionnaire"], ruleIds: ["TH-PACK-2567"], instrumentIds: ["dgtopuptax2"], gapIds: ["G-CT"], href: "/thailand/scope" }),
  p({ id: "LP-TH-DG3", sourceId: "TH-DG-3", ref: "Notification No. 3", heading: "Location of entities, dual residence and flow-through entities", jurisdiction: "TH", text: "Prescribes where a Constituent Entity or Permanent Establishment is located for Thai purposes, following the four permanent-establishment categories and the dual-resident tie-breaker of the Model Rules — treaty first, then the entity with the greater Covered Taxes paid, then the greater substance-based income exclusion — and the treatment of flow-through and reverse hybrid entities.", topics: ["thailand", "location", "situs", "dual resident", "permanent establishment", "flow-through"], ruleIds: ["TH-PACK-2567"], instrumentIds: ["dgtopuptax3"], gapIds: ["G-SITUS"], href: "/thailand/entities" }),
  p({ id: "LP-TH-DG4", sourceId: "TH-DG-4", ref: "Notification No. 4", heading: "Eligible payroll costs and eligible tangible assets", jurisdiction: "TH", text: "Eligible payroll includes salaries and wages of full-time and temporary employees and of independent contractors performing the entity's ordinary activities, bonuses, share-based remuneration, social security and other employee benefits, apportioned where the employee works in Thailand 50% or less of the time; payroll capitalised into the carrying value of tangible assets is excluded. Eligible tangible assets are measured at the average of opening and closing carrying value in the consolidated statements, include right-of-use assets and government licences for immovable property or natural resources, and exclude revaluation uplift and assets held for sale, lease or investment. Permanent-establishment payroll and assets are attributed to the PE.", topics: ["thailand", "sbie", "payroll", "tangible assets", "contractors", "50%", "capitalised", "revaluation"], ruleIds: ["TH-SBIE-MOF-1", "TH-PACK-2567"], instrumentIds: ["dgtopuptax4"], gapIds: ["G-SBIE"], href: "/thailand/sbie" }),
  p({ id: "LP-TH-DG5", sourceId: "TH-DG-5", ref: "Notification No. 5", heading: "Employees and tangible assets for UTPR allocation", jurisdiction: "TH", text: "Defines the employee count (full-time equivalent, including contractors in ordinary activities) and the net book value of tangible assets used to allocate the Total UTPR Top-up Tax Amount to Thailand, with de-duplication where a Permanent Establishment's employees or assets are also counted at the Main Entity, exclusion of Investment Entities, and reliance on the OECD Central Record to identify the jurisdictions whose IIR or QDMTT is qualified.", topics: ["thailand", "utpr", "employees", "fte", "tangible assets", "allocation", "central record"], ruleIds: ["TH-PACK-2567", "OECD-UTPR-26"], instrumentIds: ["dgtopuptax5"], gapIds: ["G-UTPR"], href: "/thailand/liability" }),
  p({ id: "LP-TH-DG6", sourceId: "TH-DG-6", ref: "Notification No. 6", heading: "Foreign-exchange conversion — three Bank of Thailand methods", jurisdiction: "TH", text: "Euro thresholds in the Decree are converted to baht at the Bank of Thailand average selling-buying midpoint for December of the year preceding the accounting period. Consolidated financial statements presented in a foreign currency are converted to baht for the threshold test at the same prescribed rate. Top-up Tax payable or refundable is converted at the commercial-bank average rate on the last business day before the tax is approved for payment or refund. Year-end rates chosen by the taxpayer are not accepted.", topics: ["thailand", "fx", "bot", "bank of thailand", "december average", "conversion", "threshold"], ruleIds: ["TH-PACK-2567"], electionIds: ["OECD_QDMTT_FX"], instrumentIds: ["dgtopuptax6"], gapIds: ["G-FX", "G-SCOPE"], href: "/thailand/fx" }),
  p({ id: "LP-TH-DG7", sourceId: "TH-DG-7", ref: "Notification No. 7", heading: "Excluded entities", jurisdiction: "TH", text: "Prescribes the conditions under which governmental entities, international organisations, non-profit organisations, pension funds, investment funds and real estate investment vehicles that are the UPE, and entities at least 95% or 85% owned by them, are excluded from the Thai Top-up Tax, mirroring Art. 1.5 of the Model Rules with Thai documentary requirements.", topics: ["thailand", "excluded entity", "pension fund", "governmental", "non-profit", "95%", "85%"], ruleIds: ["TH-PACK-2567"], electionIds: ["OECD_1.5.3"], instrumentIds: ["dgtopuptax7"], gapIds: ["G-SITUS"], href: "/thailand/entities" }),
  p({ id: "LP-TH-DG8", sourceId: "TH-DG-8", ref: "Notification No. 8", heading: "Minority-owned, investment and stateless entities", jurisdiction: "TH", text: "Prescribes the separate computation of the effective tax rate and Top-up Tax for Minority-Owned Constituent Entities and subgroups, for Investment Entities and Insurance Investment Entities, and for stateless Constituent Entities located in Thailand for the purpose of the Thai QDMTT, so that they are not blended with the majority-owned Thai entities.", topics: ["thailand", "moce", "minority-owned", "investment entity", "stateless", "separate etr"], ruleIds: ["TH-PACK-2567", "OECD-MOCE-513"], instrumentIds: ["dgtopuptax8"], gapIds: ["G-SITUS"], href: "/thailand/entities" }),
  p({ id: "LP-TH-MOF1", sourceId: "TH-MOF-1", ref: "MOF Notification No. 1", heading: "Transitional substance-based income exclusion rates by fiscal-year start", jurisdiction: "TH", text: "Sets the payroll and tangible-asset carve-out percentages for the Thai substance-based income exclusion by the calendar year in which the accounting period begins, following the OECD Art. 9.2 schedule from the Thai commencement year: 2025 — 9.6% / 7.6%; 2026 — 9.4% / 7.4%; 2027 — 9.2% / 7.2%; 2028 — 9.0% / 7.0%; 2029 — 8.2% / 6.6%; 2030 — 7.4% / 6.2%; 2031 — 6.6% / 5.8%; 2032 — 5.8% / 5.4%; 5% / 5% from accounting periods beginning in 2033. The rate is fixed by the period's start date, not its end.", topics: ["thailand", "sbie", "transitional rates", "9.4%", "7.4%", "fiscal-year start"], ruleIds: ["TH-SBIE-MOF-1", "OECD-SBIE-2026"], instrumentIds: ["moftopuptax1"], gapIds: ["G-SBIE"], href: "/thailand/sbie" }),
  p({ id: "LP-TH-BOI-1-2566", sourceId: "TH-BOI-1-2566", ref: "measures for promoted companies", heading: "BOI relief measures for promoted companies affected by the global minimum tax", jurisdiction: "TH", effectiveFrom: "2023-05-01", textKind: "summary", text: "A promoted company that is a Constituent Entity of an in-scope MNE Group may apply to convert its remaining corporate income tax exemption into a 50% reduction of the normal rate for a longer period (up to ten years in total), so that some tax is paid in Thailand and the group's Thai effective tax rate rises. The measure is investment promotion, not tax law: it does not itself alter the Top-up Tax computation and does not create a Qualified Refundable Tax Credit — Thailand has not enacted a QRTC.", topics: ["thailand", "boi", "tax holiday", "50% reduction", "conversion", "qrtc", "incentive"], ruleIds: ["TH-BOI-OPT-2566"], electionIds: ["SETR_QRTC", "SH_SBTI"], gapIds: ["G-BOI"], href: "/thailand/boi" }),
  p({ id: "LP-TH-RDNEWS-5-2026", sourceId: "TH-RD-NEWS-5-2026", ref: "secondary legislation status", heading: "Status of delegated Top-up Tax instruments", jurisdiction: "TH", effectiveFrom: "2026-05-01", textKind: "pending", text: "The Revenue Department confirms that Director-General Notifications Nos. 1–8 and MOF Notification No. 1 are in force, and that the instruments under ss 31 and 33 (detailed GloBE income and covered-tax rules) and ss 53–57 (return forms and electronic filing schema) remain to be issued, with a public hearing on the draft electronic Top-up Tax return. GMT24 treats these as coverage exceptions until the notifications are published.", topics: ["thailand", "pending", "rd news", "forms", "schema", "section 31", "section 33"], ruleIds: ["TH-PACK-2567"], instrumentIds: ["s31", "s33", "s53-57"], gapIds: ["G-FILE", "G-FANIL", "G-CT"], href: "/thailand/gap" }),

  /* ----------------------------------------------------------- Ireland */
  p({ id: "LP-IE-FA2-2023", sourceId: "IE-FA2-2023", ref: "Part 4A TCA 1997", heading: "Ireland — IIR, QDMTT and UTPR", jurisdiction: "IE", effectiveFrom: "2024-01-01", textKind: "summary", text: "Ireland transposed Council Directive (EU) 2022/2523 into Part 4A of the Taxes Consolidation Act 1997. The Income Inclusion Rule and a Qualified Domestic Top-up Tax apply for fiscal years beginning on or after 31 December 2023; the Undertaxed Profits Rule applies for fiscal years beginning on or after 31 December 2024. The legislation follows the Model Rules and Commentary, adopts the Transitional CbCR, QDMTT and UTPR safe harbours, and Ireland's IIR and QDMTT are listed on the OECD Central Record with transitional qualified status. The Knowledge Development Box is an income-based IP regime and is not a substance-based tax incentive.", topics: ["ireland", "qdmtt", "iir", "utpr", "directive", "central record", "kdb"], ruleIds: ["IE-QDMTT-2024", "OECD-SBTISH"], href: "/jurisdictions" }),

  /* ------------------------------------------------------------- Japan */
  p({ id: "LP-JP-TR-2023", sourceId: "JP-TR-2023", ref: "Corporation Tax Act Part II Ch. 1 (IIR)", heading: "Japan — Income Inclusion Rule from FY beginning on or after 1 April 2024", jurisdiction: "JP", effectiveFrom: "2024-04-01", textKind: "summary", text: "Japan's 2023 tax reform enacted the Income Inclusion Rule as a corporation tax on the 'international minimum taxable amount' of a Japanese ultimate or intermediate parent, for fiscal years beginning on or after 1 April 2024, computed on GloBE principles with the Transitional CbCR Safe Harbour. The return is due 15 months after year end (18 months for the first year). The 2025 reform added a Qualified Domestic Minimum Top-up Tax and the Undertaxed Profits Rule for fiscal years beginning on or after 1 April 2026. Japan's IIR is listed on the OECD Central Record.", topics: ["japan", "iir", "1 april 2024", "qdmtt", "utpr", "central record", "upe"], ruleIds: ["JP-IIR-2024"], electionIds: ["SH_UPE"], href: "/jurisdictions" }),

  /* ----------------------------------------------------- United States */
  p({ id: "LP-US-SBS-2026", sourceId: "US-SBS-2026", ref: "United States treatment", heading: "United States — no GloBE enactment; Side-by-Side treatment", jurisdiction: "US", effectiveFrom: "2026-01-01", textKind: "summary", text: "The United States has not enacted an Income Inclusion Rule, an Undertaxed Profits Rule or a Qualified Domestic Minimum Top-up Tax; its corporate alternative minimum tax and GILTI regime are not GloBE-qualified rules. Under the January 2026 Side-by-Side package a US-parented group may be treated side-by-side with the GloBE Rules, and the Transitional UTPR Safe Harbour treats UTPR Top-up Tax for the US jurisdiction as zero. GILTI tax is allocated to CFCs as a Blended CFC Tax Regime. US Constituent Entities of foreign-parented groups remain subject to other jurisdictions' QDMTTs, IIR and UTPR as the safe harbours permit.", topics: ["united states", "side-by-side", "utpr safe harbour", "gilti", "camt", "no enactment"], ruleIds: ["US-SBS-2026", "OECD-CT-43"], electionIds: ["SH_SBS", "SH_UTPR"], href: "/safe-harbours" }),
];
