import type { LegalSource } from "./types";

/**
 * Source register. One record per instrument the corpus paraphrases. URLs
 * are the publisher's; where oecd.org fronts a page with a browser challenge
 * the Regulatory Impact Watch reads the archive copy — the citation stays on
 * the publisher's URL.
 */

const OECD_GMT_HUB = "https://www.oecd.org/en/topics/sub-issues/global-minimum-tax.html";
const OECD_MODEL_RULES = "https://www.oecd.org/en/topics/sub-issues/global-minimum-tax/global-anti-base-erosion-model-rules-pillar-two.html";
const OECD_COMMENTARY_2026 = "https://www.oecd.org/en/publications/tax-challenges-arising-from-the-digitalisation-of-the-economy-consolidated-commentary-to-the-global-anti-base-erosion-model-rules-2026_4377e89f-en.html";
const OECD_COMMENTARY_2025_PDF = "https://www.oecd.org/content/dam/oecd/en/publications/reports/2025/05/tax-challenges-arising-from-the-digitalisation-of-the-economy-consolidated-commentary-to-the-global-anti-base-erosion-model-rules-2025_be9651c2/a551b351-en.pdf";
const OECD_GIR_2025_PDF = "https://www.oecd.org/content/dam/oecd/en/publications/reports/2025/01/tax-challenges-arising-from-the-digitalisation-of-the-economy-globe-information-return-january-2025_b03274ed/a05ec99a-en.pdf";
const OECD_GIR_2026_09_DOI = "https://doi.org/10.1787/a05ec99a-en";
const OECD_GIR_XML_PDF = "https://www.oecd.org/content/dam/oecd/en/publications/reports/2025/01/globe-information-return-pillar-two-xml-schema_3980638f/c594935a-en.pdf";
const OECD_SBS_PDF = "https://www.oecd.org/content/dam/oecd/en/topics/policy-sub-issues/global-minimum-tax/side-by-side-package.pdf";
const OECD_CENTRAL_RECORD = "https://www.oecd.org/en/topics/sub-issues/global-minimum-tax/central-record-of-legislation-with-transitional-qualified-status.html";
const OECD_CENTRAL_RECORD_PDF = "https://www.oecd.org/content/dam/oecd/en/topics/policy-sub-issues/global-minimum-tax/updated-central-record-for-purposes-of-the-global-minimum-tax.pdf";

const RD_DECREE = "https://www.rd.go.th/67365.html";
const RD_NOTIFICATIONS = "https://www.rd.go.th/68005.html";
const RD_NEWS_5_2026 = "https://www.rd.go.th/fileadmin/user_upload/news/2568eng/englishnews_5_2026.pdf";
const RD_TOPUP_MAP = "https://www.rd.go.th/fileadmin/user_upload/porsor/topuptaxreference_170269.pdf";

export const LEGAL_SOURCES: LegalSource[] = [
  /* ---------------------------------------------------------------- OECD */
  { id: "OECD-MR-2021", authority: "OECD", title: "Tax Challenges Arising from the Digitalisation of the Economy — Global Anti-Base Erosion Model Rules (Pillar Two)", short: "Model Rules", kind: "model-rules", url: OECD_MODEL_RULES, publishedAt: "2021-12-20", effectiveFrom: "2024-01-01", effectiveTo: null, language: "en", version: "2021.12", status: "in-force", note: "Chapters 1–10. The Model Rules are a common approach: they bind only where a jurisdiction enacts them. Effective date shown is the first common Fiscal Year of application." },
  { id: "OECD-COMM-2026", authority: "OECD", title: "Consolidated Commentary to the Global Anti-Base Erosion Model Rules (2026)", short: "Commentary 2026", kind: "commentary", url: OECD_COMMENTARY_2026, publishedAt: "2026-05-27", effectiveFrom: "2024-01-01", effectiveTo: null, language: "en", version: "2026.1", status: "in-force", note: "Approved and declassified by the Inclusive Framework on 11 May 2026. Incorporates the Administrative Guidance released up to the consolidation date. Supersedes the 2025 consolidation as the interpretive text. Copy on file under OECD publications." },
  { id: "OECD-COMM-2025", authority: "OECD", title: "Consolidated Commentary to the Global Anti-Base Erosion Model Rules (2025)", short: "Commentary 2025", kind: "commentary", url: OECD_COMMENTARY_2025_PDF, publishedAt: "2025-05-30", effectiveFrom: "2024-01-01", effectiveTo: "2026-04-30", language: "en", version: "2025.1", status: "superseded", note: "Kept for prior-year positions taken before the 2026 consolidation." },
  { id: "OECD-AG-2023-02", authority: "OECD", title: "Administrative Guidance on the GloBE Model Rules — February 2023", short: "AG Feb 2023", kind: "admin-guidance", url: OECD_GMT_HUB, publishedAt: "2023-02-02", effectiveFrom: "2023-02-02", effectiveTo: null, language: "en", version: "2023.2", status: "in-force", note: "Scope, income and taxes, insurance, transition, QDMTT design. Now folded into the Consolidated Commentary." },
  { id: "OECD-AG-2023-07", authority: "OECD", title: "Administrative Guidance on the GloBE Model Rules — July 2023", short: "AG Jul 2023", kind: "admin-guidance", url: OECD_GMT_HUB, publishedAt: "2023-07-17", effectiveFrom: "2023-07-17", effectiveTo: null, language: "en", version: "2023.7", status: "in-force", note: "Currency conversion, tax credits, SBIE, QDMTT Safe Harbour, Transitional UTPR Safe Harbour." },
  { id: "OECD-AG-2023-12", authority: "OECD", title: "Administrative Guidance on the GloBE Model Rules — December 2023", short: "AG Dec 2023", kind: "admin-guidance", url: OECD_GMT_HUB, publishedAt: "2023-12-18", effectiveFrom: "2023-12-18", effectiveTo: null, language: "en", version: "2023.12", status: "in-force", note: "Transitional CbCR Safe Harbour clarifications (purchase price accounting, hybrid arbitrage), filing deadlines, blended CFC allocation." },
  { id: "OECD-AG-2024-06", authority: "OECD", title: "Administrative Guidance on the GloBE Model Rules — June 2024", short: "AG Jun 2024", kind: "admin-guidance", url: OECD_GMT_HUB, publishedAt: "2024-06-17", effectiveFrom: "2024-06-17", effectiveTo: null, language: "en", version: "2024.6", status: "in-force", note: "Deferred tax liability recapture (aggregate DTL categories, five-year unclaimed accrual), divergences between GloBE and accounting carrying values, flow-through entities, securitisation." },
  { id: "OECD-AG-2025-01", authority: "OECD", title: "Administrative Guidance on the GloBE Model Rules — January 2025", short: "AG Jan 2025", kind: "admin-guidance", url: OECD_GMT_HUB, publishedAt: "2025-01-15", effectiveFrom: "2025-01-15", effectiveTo: null, language: "en", version: "2025.1", status: "in-force", note: "Article 9.1 transition attributes: deferred tax assets arising from governmental arrangements and pre-transition transactions." },
  { id: "OECD-SH-2022-12", authority: "OECD", title: "Safe Harbours and Penalty Relief: Global Anti-Base Erosion Rules (Pillar Two)", short: "Safe Harbours Dec 2022", kind: "safe-harbour", url: OECD_GMT_HUB, publishedAt: "2022-12-20", effectiveFrom: "2024-01-01", effectiveTo: null, language: "en", version: "2022.12", status: "in-force", note: "Transitional CbCR Safe Harbour, Simplified Calculations framework, transitional penalty relief. Duration extended by the 2026 package." },
  { id: "OECD-SBS-2026", authority: "OECD", title: "Inclusive Framework Side-by-Side package (January 2026): Side-by-Side Safe Harbour, Transitional UTPR Safe Harbour extension, Simplified ETR Safe Harbour, Substance-based Tax Incentive Safe Harbour, TCSH extension", short: "Side-by-Side package 2026", kind: "safe-harbour", url: OECD_SBS_PDF, publishedAt: "2026-01-15", effectiveFrom: "2026-01-01", effectiveTo: null, language: "en", version: "2026.1", status: "in-force", note: "Package agreed by the Inclusive Framework; each element takes legal effect only through domestic law or a qualified-status listing." },
  { id: "OECD-GIR-2025", authority: "OECD", title: "GloBE Information Return (Pillar Two) — January 2025", short: "GIR Jan 2025", kind: "gir", url: OECD_GIR_2025_PDF, publishedAt: "2025-01-15", effectiveFrom: "2024-01-01", effectiveTo: "2026-09-10", language: "en", version: "2025.1", status: "superseded", note: "Return template, transitional simplified jurisdictional reporting, dissemination approach. Superseded by the September 2026 edition." },
  { id: "OECD-GIR-2026-09", authority: "OECD", title: "GloBE Information Return (September 2026)", short: "GIR Sep 2026", kind: "gir", url: OECD_GIR_2026_09_DOI, publishedAt: "2026-09-11", effectiveFrom: "2024-01-01", effectiveTo: null, language: "en", version: "2026.9", status: "in-force", note: "Approved by the Inclusive Framework on 2 September 2026. Revised template with Annex A1 data points, Annex A2 explanatory guidance, Annex B exchange-of-information notification and Annex C transitional penalty relief; adds the Side-by-Side Safe Harbour election. Governs returns filed from publication for every Reporting Fiscal Year, so it is treated as in force from the first GloBE year. Copy on file under OECD publications." },
  { id: "OECD-GIR-XML", authority: "OECD", title: "GloBE Information Return — XML Schema and User Guide v1.0", short: "GIR XML v1.0", kind: "gir", url: OECD_GIR_XML_PDF, publishedAt: "2025-01-15", effectiveFrom: "2024-01-01", effectiveTo: null, language: "en", version: "1.0", status: "in-force", note: "Namespace urn:oecd:ties:globe:v2. Governs the exchange format, not the substantive rules." },
  { id: "OECD-CR", authority: "OECD", title: "Central Record of legislation with transitional qualified status", short: "Central Record", kind: "central-record", url: OECD_CENTRAL_RECORD, publishedAt: "2025-01-15", effectiveFrom: "2024-01-01", effectiveTo: null, language: "en", version: "rolling", status: "in-force", note: `Periodically updated PDF at ${OECD_CENTRAL_RECORD_PDF}. Listing confers transitional qualified status for IIR, QDMTT and QDMTT Safe Harbour purposes.` },

  /* ------------------------------------------------------------ Thailand */
  { id: "TH-DECREE-2567", authority: "TH", title: "Emergency Decree on Top-up Tax B.E. 2567 (2024)", short: "Decree B.E. 2567", kind: "decree", url: RD_DECREE, publishedAt: "2024-12-26", effectiveFrom: "2025-01-01", effectiveTo: null, language: "th", version: "2567.1", status: "in-force", instrumentIds: ["prk2567"], note: "Thai master rules: scope, 15% minimum, QDMTT / IIR / UTPR, filing, payment, audit, appeal, penalties. Official text is Thai; GMT24 paraphrases in English." },
  { id: "TH-DG-1", authority: "TH", title: "Director-General Notification on Top-up Tax No. 1 — acceptable financial accounting standards", short: "DG Notification No. 1", kind: "notification", url: RD_NOTIFICATIONS, publishedAt: "2025-06-30", effectiveFrom: "2025-01-01", effectiveTo: null, language: "th", version: "2568.1", status: "in-force", instrumentIds: ["dgtopuptax1"] },
  { id: "TH-DG-2", authority: "TH", title: "Director-General Notification on Top-up Tax No. 2 — qualified and disqualified refundable imputation taxes", short: "DG Notification No. 2", kind: "notification", url: RD_NOTIFICATIONS, publishedAt: "2025-06-30", effectiveFrom: "2025-01-01", effectiveTo: null, language: "th", version: "2568.1", status: "in-force", instrumentIds: ["dgtopuptax2"] },
  { id: "TH-DG-3", authority: "TH", title: "Director-General Notification on Top-up Tax No. 3 — location of entities, dual residence and flow-through entities", short: "DG Notification No. 3", kind: "notification", url: RD_NOTIFICATIONS, publishedAt: "2025-06-30", effectiveFrom: "2025-01-01", effectiveTo: null, language: "th", version: "2568.1", status: "in-force", instrumentIds: ["dgtopuptax3"] },
  { id: "TH-DG-4", authority: "TH", title: "Director-General Notification on Top-up Tax No. 4 — eligible payroll costs and eligible tangible assets", short: "DG Notification No. 4", kind: "notification", url: RD_NOTIFICATIONS, publishedAt: "2025-06-30", effectiveFrom: "2025-01-01", effectiveTo: null, language: "th", version: "2568.1", status: "in-force", instrumentIds: ["dgtopuptax4"] },
  { id: "TH-DG-5", authority: "TH", title: "Director-General Notification on Top-up Tax No. 5 — employees and tangible assets for UTPR allocation", short: "DG Notification No. 5", kind: "notification", url: RD_NOTIFICATIONS, publishedAt: "2025-06-30", effectiveFrom: "2025-01-01", effectiveTo: null, language: "th", version: "2568.1", status: "in-force", instrumentIds: ["dgtopuptax5"] },
  { id: "TH-DG-6", authority: "TH", title: "Director-General Notification on Top-up Tax No. 6 — foreign-exchange conversion", short: "DG Notification No. 6", kind: "notification", url: RD_NOTIFICATIONS, publishedAt: "2025-06-30", effectiveFrom: "2025-01-01", effectiveTo: null, language: "th", version: "2568.1", status: "in-force", instrumentIds: ["dgtopuptax6"] },
  { id: "TH-DG-7", authority: "TH", title: "Director-General Notification on Top-up Tax No. 7 — excluded entities", short: "DG Notification No. 7", kind: "notification", url: RD_NOTIFICATIONS, publishedAt: "2025-06-30", effectiveFrom: "2025-01-01", effectiveTo: null, language: "th", version: "2568.1", status: "in-force", instrumentIds: ["dgtopuptax7"] },
  { id: "TH-DG-8", authority: "TH", title: "Director-General Notification on Top-up Tax No. 8 — minority-owned, investment and stateless entities", short: "DG Notification No. 8", kind: "notification", url: RD_NOTIFICATIONS, publishedAt: "2025-06-30", effectiveFrom: "2025-01-01", effectiveTo: null, language: "th", version: "2568.1", status: "in-force", instrumentIds: ["dgtopuptax8"] },
  { id: "TH-MOF-1", authority: "TH", title: "Ministry of Finance Notification on Top-up Tax No. 1 — transitional substance-based income exclusion rates", short: "MOF Notification No. 1", kind: "notification", url: RD_DECREE, publishedAt: "2025-06-30", effectiveFrom: "2025-01-01", effectiveTo: null, language: "th", version: "2568.1", status: "in-force", instrumentIds: ["moftopuptax1"] },
  { id: "TH-BOI-1-2566", authority: "TH", title: "Board of Investment Announcement No. 1/2566 — measures for promoted companies affected by the global minimum tax", short: "BOI Announcement 1/2566", kind: "announcement", url: "https://www.boi.go.th/", publishedAt: "2023-05-01", effectiveFrom: "2023-05-01", effectiveTo: null, language: "th", version: "2566.1", status: "in-force", note: "Investment promotion, not tax law: lets a promoted company convert a corporate income tax exemption into a 50% reduction over a longer period." },
  { id: "TH-RD-NEWS-5-2026", authority: "TH", title: "Revenue Department news release No. 5/2026 (English) — status of Top-up Tax secondary legislation", short: "RD news 5/2026", kind: "guidance", url: RD_NEWS_5_2026, publishedAt: "2026-05-01", effectiveFrom: "2026-05-01", effectiveTo: null, language: "en", version: "2026.5", status: "pending", instrumentIds: ["s31", "s33", "s53-57"], note: `Announces the delegated instruments still to be issued. The RD's Top-up Tax reference map is at ${RD_TOPUP_MAP}.` },

  /* ------------------------------------------------ other jurisdictions */
  { id: "IE-FA2-2023", authority: "IE", title: "Finance (No. 2) Act 2023 — Part 4A Taxes Consolidation Act 1997 (Implementation of Council Directive (EU) 2022/2523)", short: "Ireland Finance (No. 2) Act 2023", kind: "law", url: "https://www.irishstatutebook.ie/eli/2023/act/39/enacted/en/html", publishedAt: "2023-12-18", effectiveFrom: "2024-01-01", effectiveTo: null, language: "en", version: "2023.12", status: "in-force" },
  { id: "JP-TR-2023", authority: "JP", title: "Japan 2023 Tax Reform Act — Income Inclusion Rule (国際最低課税額に対する法人税)", short: "Japan 2023 Tax Reform", kind: "law", url: "https://www.nta.go.jp/english/taxes/corporation/pillar2/index.htm", publishedAt: "2023-03-28", effectiveFrom: "2024-04-01", effectiveTo: null, language: "ja", version: "2023.3", status: "in-force", note: "IIR for fiscal years beginning on or after 1 April 2024. QDMTT and UTPR enacted by the 2025 reform for fiscal years beginning on or after 1 April 2026." },
  { id: "US-SBS-2026", authority: "US", title: "United States — Side-by-Side treatment under the Inclusive Framework January 2026 package", short: "US Side-by-Side 2026", kind: "guidance", url: OECD_SBS_PDF, publishedAt: "2026-01-15", effectiveFrom: "2026-01-01", effectiveTo: null, language: "en", version: "2026.1", status: "in-force", note: "The United States has not enacted the IIR, UTPR or a QDMTT. Its treatment in GMT24 flows from the OECD Side-by-Side package, not from a US statute." },
];

export function legalSourceById(id: string) {
  return LEGAL_SOURCES.find((s) => s.id === id);
}
